// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBafF6mrEvMuiLFWyEZCNAMpC9Nx1nfB_0',
    appId: '1:477056148124:web:76a49d3eb49baa5b5bc359',
    messagingSenderId: '477056148124',
    projectId: 'tily-49633',
    authDomain: 'tily-49633.firebaseapp.com',
    storageBucket: 'tily-49633.appspot.com',
    measurementId: 'G-0R2K02EPZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCogVHyPsbWKn7meggE2mHGfpHUboXm_0',
    appId: '1:477056148124:android:34c12433df4f17505bc359',
    messagingSenderId: '477056148124',
    projectId: 'tily-49633',
    storageBucket: 'tily-49633.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfTcLyXj49dXZppdfLT5ZEkVmZTws3BcA',
    appId: '1:477056148124:ios:8e7e8007a6bb06a65bc359',
    messagingSenderId: '477056148124',
    projectId: 'tily-49633',
    storageBucket: 'tily-49633.appspot.com',
    iosClientId: '477056148124-2slu7mr8q47elosskptdf0seb96rauul.apps.googleusercontent.com',
    iosBundleId: 'com.sheero.tily',
  );
}
