// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgI6nhs8K11qRORK4qXhznyqd1s_Mnzo4',
    appId: '1:116243941422:web:41cedd5a50fe71c59577bf',
    messagingSenderId: '116243941422',
    projectId: 'tily-f6b7b',
    authDomain: 'tily-f6b7b.firebaseapp.com',
    storageBucket: 'tily-f6b7b.appspot.com',
    measurementId: 'G-Y5TQ51TRED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGP_dvRqBYS8SUBjZJm9J4tNyYmKQiJqI',
    appId: '1:116243941422:android:ccf21ffd0513d62e9577bf',
    messagingSenderId: '116243941422',
    projectId: 'tily-f6b7b',
    storageBucket: 'tily-f6b7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLQ_wH9Hob1dUfhh9aSig-nJ_pnV986Po',
    appId: '1:116243941422:ios:000c50767453c2a19577bf',
    messagingSenderId: '116243941422',
    projectId: 'tily-f6b7b',
    storageBucket: 'tily-f6b7b.appspot.com',
    iosClientId: '116243941422-d1luphqtttc174bot043lrvbuu1u5dk5.apps.googleusercontent.com',
    iosBundleId: 'com.sheero.tily',
  );
}
